### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by ghost** [john-shine/mega.syno#1]
Hey John

Thanks for making this container! I installed it on my Sync and I'm connecting from a mac via integrated VNC viewer. The problem is, I can't input any special characters like the @ needed to log into my mega.co.nz account.

Clipboard doesn't work, using the macOS keyboard-viewer doesn't help either.

Can you please help out here?

**Comment by ghost** [comment]
I solved that one myself:

It is impossible to use macOS integrated VNC viewer. Get RealVNC Viewer i.e. and the keyboard input works.

**Comment by john-shine** [comment]
Sorry for late reply, RealVNC Viewer is better choose for macOS, avoid much problems...
If have problem later, ask again.
