### ISSUE TITLE
Unable to use one-way sync

### ISSUE THREAD

**Issue by elemated** [john-shine/mega.syno#10]
Hi, I am having an issue with the one-way sync functionality. I am somewhat new to this, so apologies if I am missing something. I initialized the container on my Synology NAS using the following command:

`docker run -d -p 5901:5901 -p 6080:6080 -v /volume1/localfoldersync:/home/mega/MEGA/megafoldersync/:ro johnshine/mega.syno:latest`

My understanding is the the `:ro` makes the folder on my local drive 'read-only' so that I can delete a file on the cloud and it won't be deleted locally. That's what I want to happen, but in my current configuration, MEGASync doesn't think it has permission to write to the folder (I assume because it is read-only). When I add a folder to the cloud, MEGASync says "failed: Write error." Am I doing something wrong?

Thanks for this awesome project!

**Comment by salvq** [comment]
Hi, it works as expected, you are correct about "read-only"...

However when you set sync folders on your NAS in megasync app, it will only mirror the changes you do locally (NAS). When you create folder / file within your sync folders in the cloud it will ignore it (or better say will not have a permission to mirror the change, write / create / delete etc.).
