### ISSUE TITLE
Push new version to docker hub?

### ISSUE THREAD

**Issue by tranzmatt** [john-shine/mega.syno#16]
It is possible to push an updated version to your docker hub that uses the newer megasync tools?

**Comment by whakahere** [comment]
Is it possible? I would love the new mega as the current version doesn't work if there is a shared folder. 

Any hope of getting this updated please?

**Comment by john-shine** [comment]
@tranzmatt @whakahere I’ll update ASAP. My work pc is repairing by now

**Comment by whakahere** [comment]
> @tranzmatt @whakahere I’ll update ASAP. My work pc is repairing by now

Thank you. Looking forward to the update.

**Comment by whakahere** [comment]
@john-shine Are you still looking to update this?

**Comment by john-shine** [comment]
@tranzmatt @whakahere @salvq  updated. sorry for the late.
