### ISSUE TITLE
mega folder and nas file station

### ISSUE THREAD

**Issue by TheRealHerisson** [john-shine/mega.syno#17]
Hi.

How does the mega folder list relate to the file station list in the nas? In other words how do I select a file station folder in the mega folder list?

![Screenshot 2024-05-18 at 12-31-47 MEGAsync Client](https://github.com/john-shine/mega.syno/assets/77892697/bfce1e15-4293-4ad1-be19-f4a1a257f62e)
![Screenshot 2024-05-18 at 12-34-39 CAS-Server - Synology NAS](https://github.com/john-shine/mega.syno/assets/77892697/a5bad0b3-2de7-4d85-8a1e-398e074afc57)

Thanks
Herisson

**Comment by john-shine** [comment]
U can read this article to archive your purpose: https://www.digitalocean.com/community/tutorials/how-to-share-data-between-the-docker-container-and-the-host

**Comment by TheRealHerisson** [comment]
Sorry, I can't see how that helps. If this is running Mega for the NAS, how can I see/select NAS files as seen in Filestation?
