### ISSUE TITLE
Can't see the windows

### ISSUE THREAD

**Issue by thelittlefireman** [john-shine/mega.syno#2]
Hi,
After setting my username/password and sync configuration, mega go into tray icon and i can't see or clic on it. How do you do to show it on ? or open it again ? like on your screenshot ?

**Comment by john-shine** [comment]
U can run the following code to go into terminal in docker:
`docker exec -it ${container_id} /bin/bash`

and then run:
`megasync`

It should active main window and show it. I remember not very well, try it first. hope it helps

**Comment by thelittlefireman** [comment]
thanks :) but after start  stop the container the windows is shown so i don't know if it's working. I wonder if is there a way to set a password for the vnc connection ?

**Comment by thelittlefireman** [comment]
I get answer for my question : 
the megasync command works and
for setting a password add -e vnc_password="password"

**Comment by john-shine** [comment]
Pleased to help you. Yes, vnc_password parameter can set password for vnc connect.
