### ISSUE TITLE
One / Two way sync, app update

### ISSUE THREAD

**Issue by salvq** [john-shine/mega.syno#3]
Hi John, just want to thanks for the megasync docker, great and working solution.

I am using it on QNAP as docker with a commands below if anybody is interested, you can also add to your description page.

**Two way sync (deleting either on Cloud or locally will result in sync up)**
`sudo docker run --name megasync --restart always -e DISPLAY=':1' -e HOME='/home/mega' -e USER='megasync' -d -p 5901:5901 -v /share/CACHEDEV1_DATA/Download:/megaclient-folders/ johnshine/mega.syno:latest`

**One way sync, local (deleting locally will result in sync up on Cloud but deleting on cloud will not result on delleting locally)**
`sudo docker run --name megasync --restart always -e DISPLAY=':1' -e HOME='/home/mega' -e USER='megasync' -d -p 5901:5901 -v /share/CACHEDEV1_DATA/Download:/megaclient-folders/:ro johnshine/mega.syno:latestt`

Is there any way how to update megasync within docker ? Latest version is 3.7.1, docker version 3.6.0

Thanks,
Regards,

**Comment by salvq** [comment]
For anybody that is looking to update rpm package within docker, see below process.

- Download latest version from web (desktop app, Linux, CentOS 7.0 64bit i.e. megasync-CentOS_7.x86_64.rpm)
`https://mega.nz/sync`

- copy file to docker or download to docker or skip when you download directly to docker
`# docker cp megasync-CentOS_7.x86_64.rpm DOCKER_NAME:/tmp`

- access docker as root user
`# docker exec -it --user root DOCKER_NAME /bin/bash
`
- install package from /tmp folder or wherever file is downloaded to
`# yum install megasync-CentOS_7.x86_64.rpm
`
- restart docker

Successfully works for QNAP i.e. I was able to update MEGAsync client from 3.6.0 to the latest one 3.7.1

![image](https://user-images.githubusercontent.com/43242348/49472001-a538e500-f80e-11e8-8f9f-1474e623975b.png)

**Comment by john-shine** [comment]
@salvq Update to 3.7.1 && thanks for your advice!
