### ISSUE TITLE
Upgrade to 4.1.1 - window keeps dissapearing

### ISSUE THREAD

**Issue by salvq** [john-shine/mega.syno#4]
I just upgrade (yum install) to higher version of megasync (from 3.7.1 to 4.1.1 - current one) within docker.

Megasync window shows up during start of docker however dissapear in few seconds and sometimes appearing again sometimes not (kind of random behaviour, sometimes helping to execute megasync again). Uploading and downloading works just fine even window is not showen (megasync is running on background and uploading / downloading files just fine).

After downgrade (yum downgrade) back to 3.7.1 window never dissapear, always showen.

Can you check on your end ? Is it related to VNC server ? If you need any log or anything just let me know.

Thanks

**Comment by john-shine** [comment]
> I just upgrade (yum install) to higher version of megasync (from 3.7.1 to 4.1.1 - current one) within docker.
> 
> Megasync window shows up during start of docker however dissapear in few seconds and sometimes appearing again sometimes not (kind of random behaviour, sometimes helping to execute megasync again). Uploading and downloading works just fine even window is not showen (megasync is running on background and uploading / downloading files just fine).
> 
> After downgrade (yum downgrade) back to 3.7.1 window never dissapear, always showen.
> 
> Can you check on your end ? Is it related to VNC server ? If you need any log or anything just let me know.
> 
> Thanks

Maybe megasync client just crash, so window never show. I will update megasync to lastest version soon.

**Comment by salvq** [comment]
Well, does not look like client crashing because synchronization with mega.nz servers works just fine even UI window is not showen / visible.

I tried many times to change content among synchronized folders and all the files are being transmitted without any issue. You just can not see the progress and change settings due to no UI window.

**Comment by john-shine** [comment]
> Well, does not look like client crashing because synchronization with mega.nz servers works just fine even UI window is not showen / visible.
> 
> I tried many times to change content among synchronized folders and all the files are being transmitted without any issue. You just can not see the progress and change settings due to no UI window.

When try to upgrade to new version, I reproduce this issue. It seens like megasync buildin bug. I will try to fix by avoid method in those days.

**Comment by john-shine** [comment]
@salvq Fixed in current latest version 1.2.
