### ISSUE TITLE
Mega Window Not Visible

### ISSUE THREAD

**Issue by UnhealthyKraken** [john-shine/mega.syno#5]
I have just done a new install of this, I managed to sign in after a few restarts so the menu showed, but now after that its just a blank screen

**Comment by UnhealthyKraken** [comment]
Re-installing gave a temp fix, but I have notied it is extremely resource hungry, and will eventually freeze

**Comment by john-shine** [comment]
The temp fix see [issue2](https://github.com/john-shine/mega.syno/issues/2#issuecomment-421593748) . I'm writing a Qt program in those days, should fix this problem not too long.

**Comment by john-shine** [comment]
@UnhealthyKraken Problem has been fixed in v1.2
