### ISSUE TITLE
vnc_password not working

### ISSUE THREAD

**Issue by ivaniskandar** [john-shine/mega.syno#7]
Hi! Thanks for this helpful docker image. It's running correctly as it should except one thing, the VNC access password.

I've set the vnc_password environment variable from the docker control panel, it shows password dialog when connecting but it doesn't take the correct password, instead it takes empty password. My current setup is latest DSM (6.2.2-24922 Update 4) and latest Docker from the Package Center (18.09.0-0506).

Let me know if I did a mistake.

**Comment by salvq** [comment]
I can confirm the vnc_password variable does not work correctly.

`$ sudo docker run -d -e vnc_password="test" -p 5901:5901 johnshine/mega.syno:latest -v /share/Download/ /megaclient-folders/:ro`

I tried to add variable however it will not allow me to connect, password dialog after I enter either empty password or test it says `no password configured for VNC auth`

You may try to update docker file and rebuild the image, you can find the pass in `ARG vnc_password=""`

**Notes:**
ARG variable are accessible during image build, ENV for future running containers

**Comment by john-shine** [comment]
Thanks for your feedback. it's a bug by mistake && fixed in version 1.5
