### ISSUE TITLE
How to access folder ?

### ISSUE THREAD

**Issue by nonogt** [john-shine/mega.syno#9]
Hello !

I have a DS218+, I want to sync a folder, it appears simply as "/myfolder" in File Station, but I can't find it in your Megasync...

I am a noob in NAS and programming, so I need help !

**Comment by dimchen** [comment]
under volumn , under mount path , you have to set it to /home/mega/MEGAsync

**Comment by john-shine** [comment]
It should be:
sudo docker run -d -p 5901:5901 -p 6080:6080 -v /volumexxx/myfolder:/home/mega/MEGA johnshine/mega.syno:latest

U should replace volumexxx with real volume number.
